### ISSUE TITLE
Consider Replacing with gradle-extra-configurations-plugin

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/propdeps-plugin#2]
I wonder if we have considered replacing this with https://github.com/nebula-plugins/gradle-extra-configurations-plugin? This would mean we would not have to maintain the propdeps plugin in anymore.

cc @wilkinsona @philwebb

**Comment by wilkinsona** [comment]
It seems to require the configuration of a Maven Deployer, for example:

```
uploadArchives {
    repositories {
        mavenDeployer {
            //…
        }
    }
}
```

Otherwise it fails trying to find one:

```
Caused by: groovy.lang.MissingPropertyException: Could not find property 'mavenDeployer' on repository container.
	at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
	at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
	at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:97)
	at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler_Decorated.getProperty(Unknown Source)
	at nebula.plugin.extraconfigurations.OptionalBasePlugin$_configureMavenPlugin_closure4_closure12.doCall(OptionalBasePlugin.groovy:118)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	... 77 more
```

**Comment by rwinch** [comment]
@wilkinsona Thanks for sharing this finding. Perhaps this is something we could work with the nebula team on. For me a small investment like that would be worth it if we didn't have to maintain the plugin.

**Comment by philwebb** [comment]
It would certainly be nice to not have to support propdeps. As long as the IDE generation works I'd be happy to switch. I'm guessing [GRADLE-784](http://issues.gradle.org/browse/GRADLE-784) won't ever get fixed.
